---
# Role tasks

- block:
    - name: create mount points
      file:
        path: "{{ item.path }}"
        state: directory
      when:
        - mounts_create_paths
        - item.state | default(mounts_defaults.state) != "absent"
      loop: "{{ mounts }}"
      loop_control:
        label: "{{ item.path }}"

    - name: setup mounts
      mount:
        backup: >-
          {{ item.backup | default(mounts_defaults.backup) | default(omit) }}
        boot: >-
          {{ item.boot | default(mounts_defaults.boot) | default(omit) }}
        dump: >-
          {{ item.dump | default(mounts_defaults.dump) | default(omit) }}
        fstab: >-
          {{ item.fstab | default(mounts_defaults.fstab) | default(omit) }}
        fstype: >-
          {{ item.fstype | default(mounts_defaults.fstype) | default(omit) }}
        opts: >-
          {{ item.opts | default(mounts_defaults.opts) | default(omit) }}
        passno: >-
          {{ item.passno | default(mounts_defaults.passno) | default(omit) }}
        path: >-
          {{ item.path | default(mounts_defaults.path) | default(omit) }}
        src: >-
          {{ item.src | default(mounts_defaults.src) | default(omit) }}
        state: >-
          {{ item.state | default(mounts_defaults.state) | default(omit) }}
      loop: "{{ mounts }}"
      loop_control:
        label: "{{ item.path }}"
  tags:
    - role::mounts
