---

- name: Verify
  hosts: molecule_hosts
  gather_facts: no
  tasks:
    - name: Read /etc/fstab file
      ansible.builtin.command: cat /etc/fstab
      changed_when: no
      register: read_fstab_result

    - name: Check that /etc/fstab contains required mounts
      ansible.builtin.assert:
        that:
          - read_fstab_result.stdout is search("/dev/disk0.*/mnt/disk0.*ext4")
          - read_fstab_result.stdout is search("/dev/disk1.*/mnt/disk1.*ext4")
          - read_fstab_result.stdout is not search("/mnt/disk2")
